export const GET_CURRENCIES = 'GET_CURRENCIES';
export const FAILED_TO_GET_CURRENCIES = 'FAILED_TO_GET_CURRENCIES';
export const GET_CALCULATED_RATES = 'GET_CALCULATED_RATES';
export const FAILED_TO_GET_CALCULATED_RATES = 'FAILED_TO_GET_CALCULATED_RATES';
